### ISSUE TITLE
Nelze změnit I2C adresa u SDP3x sezoru

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TFASPDIMU01#4]
SDP3x má addr pin přímo připojený do GND, Díky tomu nelze změnit I2C adresa SDP3x senzoru. Je to trochu komplikace v případě, že se v IMU jednotce nastaví mostování I2C (např kvůli nastavení senzoru). A na sběrnici je připojený jiný SDP3x senzor se stejnou adresou.

**Comment by kaklik** [comment]
Adresa se nastavuje velikostí rezistoru z ADDR pinu do GND, podle tabulky z datasheetu: 

![image](https://user-images.githubusercontent.com/1194177/109285759-c0de9a80-7821-11eb-9124-0b3f9efd573e.png)

**Comment by ChroustJan** [comment]
@roman-dvorak kolik adres by jsme chtěli? 2 nebo 3?

**Comment by kaklik** [comment]
Vyřešeno v [nové verzi](https://github.com/ThunderFly-aerospace/TFASPDIMU02).
