### ISSUE TITLE
Oscilace signálů při zatížení větší kapacitou - délkou vodičů

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFASPDIMU01#5]
Tak pokud se zapojí TFSLOT do série s TFRPM tak se s docela velkou pravděpodobností na SDA stane tohle (za pozornost stojí zejména to, že generované obdélníky jsou na 6 MHz, tedy naprosto mimo pásmo běžné I2C signalizace): 

![Newfile4](https://user-images.githubusercontent.com/1194177/109212157-77556780-77af-11eb-9a3e-c72ed5519773.png)

Vznikne to následující sekvencí příkazů: 

    icm20948i2c start -X -b 4

V tomto okamžiku je sběrnice ještě v pořádku. Rozbije se až následujícím příkazem: 

    sdp3x_airspeed start  -X

Pokud se TFASPDIMU odpojí a připojí zpátky, tak se sběrnice zotaví a jsou na ní normální data. 

![Newfile5](https://user-images.githubusercontent.com/1194177/109212478-dca95880-77af-11eb-85f9-eacbd6311af4.png)

Pokud se k autopilotovi připojí pouze TFASPDIMU na krátké dráty (15cm), tak I2C  částečně funguje. Zákmity vznikají jen mezi bity, kdy je sběrnice zřejmě buzena pouze pull-upy. 

![Newfile6](https://user-images.githubusercontent.com/1194177/109214237-e59b2980-77b1-11eb-9e50-ffacbe7a41b8.png)

![image](https://user-images.githubusercontent.com/1194177/109213708-3a8a7000-77b1-11eb-92c2-44a6b43d0665.png)

Jedná se tak zjevně o HW problém.

_Originally posted by @kaklik in https://github.com/ThunderFly-aerospace/TF-G2/issues/88#issuecomment-786179307_

**Comment by kaklik** [comment]
Příčinou problému je obvod [TXS0108E](https://www.ti.com/lit/ds/symlink/txs0108e.pdf), který obsahuje  "one shot accerator", který zrychluje náběžnou hranu připojením push-pull budiče na dobu 30ns. 

Konstrukce tak narazila na limitaci v jeho datasheetu. "TI recommendsthatthis lumped-loadcapacitanceisconsideredin orderto avoidone-shotretriggering,bus contention,outputsignaloscillations,or otheradversesystem-levelaffects"

Tato situace je překvapivá i proto, že použitý obvod je podle TI [doporučen pro použití jako I2C translator](https://www.ti.com/logic-circuit/voltage-level-translation/auto-bidirectional-voltage-translation/products.html#p848=8;8)

Tento obvod ale bohužel nejde deaktivovat. Takže jediné řešení zřejmě je najít nějakou náhradu, která se aktivně nesnaží o zrychlování signálových hran. 

Tyto alternativy ovšem bohužel nejsou pinově záměnné za současný obvod.  
Například

- [GTL2003](https://www.nxp.com/docs/en/data-sheet/GTL2003.pdf)
- [N74GTL2003](https://www.ti.com/lit/ds/symlink/sn74gtl2003.pdf)

**Comment by kaklik** [comment]
Tak jsem zjistil, že zákmity mají největší amplitudu na vnější I2C sběrnici směrem do autopilota, jak je ostatně vidět i na obrázku výše. 

![Newfile7](https://user-images.githubusercontent.com/1194177/109296990-8da40780-7831-11eb-900b-bcc7aa9cf62d.png)

Zkusil jsem proto do série s konektorem na vnější sběrnici zapojit rezistor 82 Ohm.  Pull-upy interní sběrnice byly odebrány v souladu s issue #6. 

![DSC00488](https://user-images.githubusercontent.com/1194177/109299332-39028b80-7835-11eb-8608-335125dfb124.JPG)

Zákmity tím úplně zmizely. 

![Newfile8](https://user-images.githubusercontent.com/1194177/109297777-d60ff500-7832-11eb-8a95-ecd6831371b7.png)

Stejnou úpravu je zřejmě potřebné udělat na všech výstupních vodičích.  Hodnota 82 Ohm je zvolena náhodně jako hodnota rezistoru, který jsem měl zrovna k dispozici, je poměrně pravděpodobné, že bude stačit hodnota menší. Například 33 Ohm.

**Comment by kaklik** [comment]
Dnes jsem testoval zda [TFI2CEXT01](https://github.com/ThunderFly-aerospace/TFI2CEXT01). Je náhradou za přidání tlumících rezistorů z komentáře https://github.com/ThunderFly-aerospace/TFASPDIMU01/issues/5#issuecomment-786612154

Výsledkem je, že není. V případě použití v kombinaci s [USBI2C01A](https://www.mlab.cz/module/USBI2C01A) se situace dokonce zhorší. Z pohledu software se situace projevuje tak, že [program](https://github.com/MLAB-project/pymlab/blob/dev/examples/windgauge03a_example.py) přečte náhodné ID z čipu SDP33, který v důsledku toho správně neidentifikuje. Následně se rozpadne celá komunikace na chybu "I2C Error".
Spuštění programu lze vzápětí opakovat se stejným výsledkem (Ale obvykle jiným ID SDP33). 

Stejný kus TFASPIDIMU při připojení přes [TFRPM01](https://github.com/ThunderFly-aerospace/TFRPM01/) funguje normálně. (Bez změny osazených součástek oproti stavu z výroby).
Avšak při přidání TFI2CEXT01 před TFASPIDIMU opakovatelně přestane fungovat.

U autopilota CUAV V5+ je však situace jiná. Zde  [TFI2CEXT01](https://github.com/ThunderFly-aerospace/TFI2CEXT01) zřejmě nějakým způsobem pomáhá, neboť je možné spolehlivě provozovat TFASPIDIMU připojený přes 30cm kablík k TFI2CEXT01 a následně do autopilota přes ~15cm kablík. Tudíž například toto je funkční sestava: 

![20210609_212953](https://user-images.githubusercontent.com/1194177/121430609-9b147600-c978-11eb-839a-8da4e9ba2307.jpg)

V případě autopilota ale testování komplikuje zatím neopravený [bug v PX4](https://github.com/PX4/PX4-Autopilot/issues/17579), který způsobuje že pro testování s autopilotem je potřeba v  TFASPIDIMU přehodit rezistor z pozice R1 na pozici R2. (Aby se změnila adresa čipu icm20948i2c na 0x69, kterou má autopilot hardcodovanou). V důsledku toho byl s autopilotem otestován pouze jeden kus TFASPIDIMU, který má [odebrány všechny pullupy](https://github.com/ThunderFly-aerospace/TFASPDIMU01/issues/6) a přidány tlumící sériové rezistory 62 Ohm na externí SDA a SCL signály.  Sestava ale funguje i bez těchto tlumících rezistorů, pouze s odstraněnými pull-upy. Tuto variantu má nyní @slimonslimon namontovanou na [TF-AEROSCALE](https://github.com/ThunderFly-aerospace/TF-AEROSCALE)

Ve všech zde popisovaných případech jsem na osciloskopu kontroloval signály SDA a SCL. Průběhy byly velmi hranaté bez morfologických znaků, ze kterých by bylo možné vysvětlit nefunkčnost v popisovaných případech. 

Kromě nefunkčního stavu v kombinaci s TFI2CEXT01 jsem ještě narazil na celkem tři kusy TFASPIDIMU, které nefungovaly  v žádné situaci. U nich předpokládám, že mají nějaké HW výrobní chyby. 

Dalšími kroky proto je:

- [ ] Zkusit osciloskopem nasnímat celý průběh signálu na obou kanálech. (k tomu by asi bylo potřeba TFI2CEXT01 upravit tak, aby měl duplicitní konektory) zde je asi potřeba pomoc od @ChroustJan. 
- [x] Zkusit najít chybu na úplně nefungujících kusech TFASPIDIMU, kde napřiklad aktivace AUX sběrnice vede k zaseknutí SCL signálu na nule.

**Comment by kaklik** [comment]
Tak tři nefunkční kusy měly na sobě výrobní vady vesměs způsobené špatným zaletováním na různých místech. Nejčastěji u IO. 

Dále podle [tohoto dokumentu](https://www.ti.com/lit/an/scea060/scea060.pdf). Použitý translátor série TXS vůbec nemá výstupní buffer. Jeho vnitřní zapojení odpovídá tomuto schéma: 

![image](https://user-images.githubusercontent.com/1194177/123006270-b4291800-d3b7-11eb-8368-040fd0790cac.png)

Od takto konstruovaného translátoru asi nelze očekávat, že bude fungovat dobře v kombinaci s dlouhým vedením. Neboť to znamená, že koncové zařízení v tomto případě snímače [SDP33](https://docs.rs-online.com/3cff/0900766b81643b7b.pdf) stáhne celé vedení na logickou nulu i včetně všech parazitních zátěží. Proudová zatížitelnost ani napěťové rozhodovací úrovně však v datasheetu Sensirionu nejsou specifikovány. Nelze tak určit zda primární problém není přetížení těchto pinů. 
V každém případě by to zřejmě chtělo v další verzi tuto část vyřešit jinak. Ideálně za použití bufferu, který bude oddělovat vnitřní a vnější sběrnici, aby od čidel na desce nebyla vyžadována schopnost utáhnout celou délku sběrnice. 

Tato záležitost může být problémem zejména u obvodu [ICM-20948](https://3cfeqx1hf82y3xcoull08ihx-wpengine.netdna-ssl.com/wp-content/uploads/2016/06/DS-000189-ICM-20948-v1.3.pdf), kde to podle tabulky v jeho datasheetu na str. 14 vypadá, že maximální budící proud sběrnice, který poskytuje je 6mA. 

![image](https://user-images.githubusercontent.com/1194177/123007744-f5bac280-d3b9-11eb-8904-4061777a0e8c.png)

To je na krátkou sběrnici na malém PCB určitě dostačující. Pro vedení signálů po vodičích mimo plošný spoj, ale nikoliv.

**Comment by kaklik** [comment]
Vzhledem  k aktuální situaci, kdy se ani po několika pokusech nepodařilo vyřešit kmitání signálu změnou rezistorů. Zároveň se mi nepodařilo najít žádný translator, který by uměl jak SPI tak i I2C sběrnici. 
Navrhoval bych proto možnost připojení na SPI u TFASPDIMU zrušit.  Místo toho vytvořit variantu pouze s I2C konektorem podle Pixhawk standardu. 

I2C vyvést ven z plošného spoje pomocí obvodu [PCA9509](https://cz.mouser.com/datasheet/2/302/PCA9509P-1127567.pdf), který našel @roman-dvorak  nebo případně pomocí obvodu [PCA9617A](https://www.nxp.com/docs/en/data-sheet/PCA9617A.pdf), který by měl být lepší a umožňovat větší zatížení sběrnice, ale zároveň je zřejmě hůře dostupný. 

Při odstranění současného translátoru zůstává otázkou, jak se vypořádat s připojením I2C na senzor SDP33.  Jeho připojení přímo na externí sběrnici asi není vhodné, kvůli celkové odolnosti zařízení.  Zároveň ale ICM-20948, má logické úrovně 1.8V a u SDP3x není bohužel napsáno, jaké logické úrovně vyžaduje.    Je tak možné buď vyzkoušet připojení na 1.8V logiku a ověřit, že komunikace funguje. Nemusí to však být řešení funkční přes celý výrobní rozptyl senzorů SDP3x.  Je tak možná lepší postupovat konzervativně a mezi  ICM-20948 a SDP3x dát ještě jiný napěťový translator na I2C.  Nevýhodou takového řešení je, že DPS pak asi nebude možné výrazně zmenšit.

**Comment by slimonslimon** [comment]
Co se podívat jak to řeší konkurence která nabízí spd3xx jen jako rychlosní senzor PX4 ?

**Comment by ChroustJan** [comment]
@kaklik nedá se někam napsat na podporu?  Jinak já taky definici nenašel.

**Comment by kaklik** [comment]
Problém je technicky vyřešený v nové verzi [TFASPDIMU02](https://github.com/ThunderFly-aerospace/TFASPDIMU02)
