### ISSUE TITLE
Odstranit nadbytečné pull-upy na interní sběrnici

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFASPDIMU01#6]
Level-translator obsahuje interní pull-upy. Proto jsou rezistory R6, R7 a R8 a R9 nadbytečné.

**Comment by kaklik** [comment]
Je potřeba ověřit, zda situace pro R4 a R5 není podobná.

**Comment by kaklik** [comment]
Tak ani rezistory R4 a R5 nejsou potřeba. 

Vypadá to však, že pull-upy musí být na vstupu externí sběrnice, kde naopak úplně chybí.

**Comment by ChroustJan** [comment]
Nové zapojení s TCA9617A.
